name: docker

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: git.allievi.xyz/${{ gitea.repository }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: git.allievi.xyz
          username: casta
          password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: git.allievi.xyz/${{ gitea.repository }}:latest